---
title: "Titanic"
author: "Winston Saunders"
date: "December 31, 2014"
output: html_document
---



```{r "get data"}

## this section gets the data and loads it into training and testing data files

        ##set working directory

        setwd("/Users/winstonsaunders/Documents/TitanicKaggle")

        ## get data sets
        training <- read.csv("train.csv", na.strings=c("NA", ""))
        testing <- read.csv("test.csv", na.strings=c("NA", ""))

```



```{r "First model" }

## This is a first simple model

        ## create data sub partition

        require(caret)
        set.seed(8675309)
        xx <- createDataPartition(y=training$Survived, p=0.80, list=FALSE)
        train1<-training[xx,]
        test1<-training[-xx,]


        ##Define training and test sets

        train1 <- train1[,c("Survived","Sex", "Age", "Fare")]
        test1 <-   test1[,c("Survived","Sex", "Age", "Fare")]


        ##simplify Age column by bucketing
        ## group in multiples of 5*n+1 (1, 6, 11, ...)
        train1$Age <- 5*round(train1$Age/5,0)+1

        ## set up training control

        control1 <- trainControl(method = "cv", number = 4, allowParallel = TRUE)

        ## model using random forest
        model1 <- train(Survived~., data = train1, method="rf", trControl = control1, prox=FALSE)

        prediction1 <- predict(model1, test1)



        prediction1[prediction1<0.5]<-0
        prediction1[prediction1>=0.5]<-1
        prediction1<-as.factor(prediction1)

table(prediction1)

        confusionMatrix(test1$Survived, prediction1)

test1$Survived

```


